version: '3.9'

volumes:
  postgres_data:
  redis_data:

services:
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: deployment/build/Dockerfile
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql - need to use our migrations here
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/var/lib/redis/data
    ports:
      - "6379:6379"
