name: Deploy

on:
  push:
    branches: [ deploy ]

jobs:
  # linter
  # tests
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

#      - name: 'Create env file'
#        run: |
#          echo "${{ secrets.ENV_FILE }}" > .env

      - name: 'Build Docker image'
        run:
          sudo docker build -t shelby12/roamly:${GITHUB_SHA::8} -f ./cmd/app/Dockerfile . &&
          sudo docker tag shelby12/roamly:${GITHUB_SHA::8} shelby12/roamly:latest

      - name: 'Push Docker image'
        run:
          docker push shelby12/roamly:latest &&
          docker push shelby12/roamly:${GITHUB_SHA::8}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pull docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: 212.111.86.198
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker pull shelby12/roamly:latest

      - name: Run backend
        uses: appleboy/ssh-action@master
        with:
          host: 212.111.86.198
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            sudo docker compose stop
            sudo docker compose up -d