name: Deploy

on:
  push:
    branches: [ deploy ]

jobs:
  # linter
  # tests
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: 'Build Docker image'
        run:
          sudo docker build -t backend:${GITHUB_SHA::8} -f ./cmd/app/Dockerfile . &&
          sudo docker tag backend:${GITHUB_SHA::8} backend:latest

      - name: 'Push Docker image'
        run:
          docker push shelby12/roamly:latest &&
          docker push shelby12/roamly:${GITHUB_SHA::8}